language: minimal

services:
    - docker

env:
    - REPO="donnellans/html2x" Dir-html2x="./html2pdf" CONTAINER="test"

before_install:
    - docker pull debian:stable-slim
    - docker build -f "${Dir-html2x}/Dockerfile" -t $REPO ${Dir}

script:
    - docker run --name "$CONTAINER" $REPO

after_error:
    - docker logs $CONTAINER

after_failure:
    - docker logs $CONTAINER
