language: minimal

services:
    - docker

env:
    global:
        - REPO_html2x="donnellans/html2x" Dir_html2x="${TRAVIS_BUILD_DIR}/html2pdf" CONTAINER_html2x="test"
        - REPO_logo="donnellans/logo" Dir_logo="${TRAVIS_BUILD_DIR}/logo" CONTAINER_logo="test"

before_install:
    - docker pull debian:stable-slim
    - docker build -f "${Dir_html2x}/Dockerfile" -t ${REPO_html2x} ${Dir_html2x}
    - docker build -f "${Dir_logo}/Dockerfile" -t ${REPO_logo} ${Dir_logo}

script:
    - docker run --name "${CONTAINER_html2x}" ${REPO_html2x}
    - docker run --name "${CONTAINER_logo}" -v"${Dir_logo}":/data ${REPO_logo} openscad -o test.png --imgsize=1220,1080 /data/include-Module-IBMlogo3D.scad 


after_error:
    - docker logs ${CONTAINER_html2x}
    - docker logs ${CONTAINER_logo}

after_failure:
    - docker logs ${CONTAINER_html2x}
    - docker logs ${CONTAINER_logo}