# Site settings
title: Sean Donnellan
twitter_username: donnellan_sean
name: Sean Donnellan

# Build settings
markdown: kramdown

#comment out this line when ready (no longer draft)
status: 
  overall: --- Draft ---
  sections: 
    - navbar - Done
    - Intro - Early Draft
    - Buzzwords - Done
    - Patents - Done
    - Publications - AWOL
    - Badges - Requires formating, contents done
    - Employer history - Done, requires content review
    - GitHub - Skeleton done, need to add more github content from local systems
    - Projects - Skeleton done, contents AWOL
    - additional information - skeleton done, content mostly AWOL

#User specific content
#Links that will appear in the navbar
primarylinks:
  - title: GitHub
    url: https://github.com/donnels
  - title: LinkedIn
    url: https://de.linkedin.com/in/sean-donnellan-03601b4a
  - title: Acclaim
    url: https://www.youracclaim.com/users/sean-donnellan.faa56e53
  - title: Research and publications
    url: https://www.researchgate.net/profile/Sean_Donnellan3/research

# Introduction section
intro: |
  I am an IT architect with 25+ years experience working in technology. 
  I have primarily worked as an IT infrastructure architect, 
  but have worked across a broad range of technologies 
  thereon: Cisco, ACI, Juniper, AIX, Linux, Ansible, DC infrastructure, and most recently NEO4J. 
  As well as spending a reasonable amount of time building Cloud Infrastructure. 
  <br/><br/>
  I have worked in large scale data center migration, management, 
  and governance roles across Europe and globally.

#Buzzword Languages
languages:
  - Bilingual
  - English
  - German

#Buzzword skills
skills:
 - IT Architect
 - IT Network Architect
 - IT Security Architect
 - IT Infrastructure Architect
 - Data Center Architecture
 - security governance
 - security policy
 - automated documentation
 - CISSP
 - AIX Advanced Technical Expert
 - Linux
 - NEO4J
 - MQTT
 - IOT
 - Juniper
 - Cisco
 - IBM Cloud
 - IBM
 - travis
 - docker
 - python
 - shell scripting
 - docker compose
 - openscad
 - git
 - UML
 - CI/CD
 - Raspberry Pi
 - ESP8266/ESP32
 - Arduino
 - IPv6
 - IPv4
 - penetration testing
 - slack
 - agile
 - ansible
 - Cloud Computing
 - Data Center Relocation
 - Virtualization
 - Network Security
 - Virtual Teams
 - Data Center
 - IT Service Management
 - ITIL
 - IT Management
 - Disaster Recovery
 - Patents
 - Solution Architecture
 - Enterprise Architecture
 - High Availability
 - Storage Area Networks
 - VMware 
 - Firewalls

#Employers and summary Work experience
roles:
 - title: IT infrastructure architect
   start: 2000
   end: Ongoing
   employer: IBM
   description: |
    10/2000 - To date </br>
    IBM, Germany </br>
    IT Architect </br>
    Achievements- </br>
     Patent application on a Method and system to enable and accelerate live and near-live migration of virtual machines and their associated storage across networks </br>
      and numerous further patent applications and granted patents,  </br>
       Author of Redbook and redpiece on iDataPlex, </br>
       On Demand Data Center Services (ODCS)- Universal Mgmt. infrastructure (UMI) Dual data center design, </br>
       Firewall looking glass design, </br>
       Universal web hosting server farm (USF) firewall mgmt. and improvement, </br>
       Extranet design, </br>
       Enterprise data centre firewall placement, </br>
       Cloud Virtualization Design and security. </br> 
    Roles- IT Architect  </br>
    Managers- Reiner Lauster from 15/10/2000 to 28/2/2004 </br>
    Mark Dietrich from 1/3/2004 to 31/8/2004 </br>
    Peter John from 1/9/2004 to 31/8/2006 </br>
    Joerg Hess from 1/9/2006 to 30/6/2007 </br>
    Peter John from 1/7/2007 to 28/4/2009 </br>
    Antonio Aliatakis 1/5/2009 to 31/12/2009 </br>
    Nicola Nicolic 1/1/2010 to 31/1/2010 </br>
    Gerhard Eikmeier 1/2/2010 and on.
 - title: System Engineer
   start: 2000
   end: 2000
   employer: Self Employed
   description: |
    04/2000 - 10/2000 </br>
    Self Employed Consultant, Germany </br>
    Freelance IT Security and Network Consultant </br>
    Achievements- Diverse customer projects and firewalls. </br>
    Roles- Consultant.
 - title: Senior Engineer
   start: 1995
   end: 2000
   employer: Sysdat GmbH
   description: |
    02/1995 - 04/2000 </br>
    SYSDAT GmbH, Germany </br>
    Senior Consultant IT Security </br>
    Achievements- </br>
     Corporate firewall design, </br>
     Unix Automation,  </br>
     High Availability, </br>
     Creation of Firewall Dept. </br>
    Roles- </br>
     Head of firewall team, </br>
      Consultant, </br>
      3rd level support for- AIX/UNIX, </br>
      Internet protocol (IP), </br>
      and Internet related issues. </br>
    Manager- Michael Brueckner.
 - title: Translator
   start: 1991
   end: 1995
   employer: Self employed
   description: |
    German English and English German translations related to the automotive industry.

#Education is required
education:
 - level: Leaving Certificate
   date: 1990
   subject: Sutton Park
   school: Sutton Park School Howth Dublin Ireland

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#     optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#List of interesting Github repo/projects to include - optional
github:
 - donnels/donnels.github.io
 - donnels/vacuumpreamp

#test acclaim section
acclaim:
   profileurl: https://www.youracclaim.com/users/sean-donnellan.faa56e53
   badges:
    - title: na
      badgeId: 0e291753-a126-49bb-b674-d839ec78ddf5
      issuedBy: na
    - title: na
      badgeId: 2db8b10a-be11-48ea-82ae-2a84b441e63a
      issuedBy: na
    - title: na
      badgeId: 804154e3-ecf2-441b-959f-487553975b0a
      issuedBy: na
    - title: na
      badgeId: 90bf777f-d7dc-430e-91a0-b61a4b92e910
      issuedBy: na
    - title: na
      badgeId: 093081a4-03a0-414d-ba99-7c760b5d522a
      issuedBy: na
    - title: na
      badgeId: 34ba89a3-4824-41dd-8133-35aea4119714
      issuedBy: na
    - title: na
      badgeId: 24a9a8e3-12ce-4d12-8480-f0536077a033
      issuedBy: na
    - title: na
      badgeId: 0552e76a-e34d-4af3-b8a8-d16486bebad5
      issuedBy: na
    - title: na
      badgeId: 8f0e3f96-07c9-4e46-aca1-d57d5fdecbb2
      issuedBy: na
    - title: na
      badgeId: 45421933-b8d3-47aa-90ef-171cacdfbb9f
      issuedBy: na
    - title: na
      badgeId: ed1628c5-4f68-4e87-8eb7-4faaa67e7be5
      issuedBy: na
    - title: na
      badgeId: 23f12439-9421-499a-8db5-3e77a56916cd
      issuedBy: na
    - title: na
      badgeId: 53a11686-0191-4d6b-97a2-f6f162ae4792
      issuedBy: na
    - title: na
      badgeId: 3407f901-8e09-47c3-afe4-25f6ad5e278f
      issuedBy: na
    - title: na
      badgeId: d49b429f-ac7a-42c7-99e1-8f04ec3c590e
      issuedBy: na
    - title: na
      badgeId: 2379495f-dfcc-4617-802f-3743c161910e
      issuedBy: na
    - title: na
      badgeId: 9641d549-4c8b-4cc6-a585-cfef3ad347a6
      issuedBy: na
    - title: na
      badgeId: d7db0e2a-670a-4ce7-bcda-3b68eacf31b3
      issuedBy: na
    - title: na
      badgeId: 8453e0d3-b9ae-4156-81bd-bb37308266b2
      issuedBy: na
    - title: na
      badgeId: 37215f2d-4209-44fc-ac1f-74d7a3f82b15
      issuedBy: na
    - title: na
      badgeId: 6b987988-3e18-45d3-8349-b1543d197678
      issuedBy: na

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>Cloud platforms</strong>: I have primarily used IBM/CMS and IBM/Softlayer. I have experience setting up, configuring and running the network intra- and inter-connectivity and security. From underlay, through LAN and WAN, to overlay.<br/><br/>
  <strong>Data analysis</strong>: Through DC projects, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
  <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked primarily with Git and Travis. I have experience with an array of testing tools and technologies.<br/><br/>
  <strong>IOT</strong>: I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including MQTT, NEO4J, a selection of micro controllers (esp8266, esp32, arduino), Raspberry Pi, and KNX/EIB. <br/><br/>     
  <strong>Publications</strong>: <br/>
  Implementing an IBM System x iDataPlex Solution, 2009, ISBN/ISSN 0738432520<br/>
  Building an Efficient Data Center with IBM iDataPlex, 2008, REDP-4418-00<br/>
  Dual Data Center - Shared converged PoD, 2005, IBM ICM AssetWeb<br/><br/>

#test section not yet in templates
patents:
  - patent:
    title: Enablement and acceleration of live and near-live migration of virtual machines and their associated storage across networks 
    ID: US8429651B2
    link: https://patents.google.com/patent/US8429651B2/en?q=inventor;sean&inventor=donnellan&oq=inventor;sean+donnellan
    abstract: |
      A virtual machine is migrated between a source cloud and a destination cloud. A temporary storage is mounted to a partition management firmware of the source cloud and to a partition management firmware of the destination cloud. A first storage location migration migrates the virtual machine from the source cloud to the at least one temporary storage. A second storage location migration migrates the virtual machine from the at least one temporary storage to final destination storage of the destination cloud. The temporary storage is then unmounted from the partition management firmware of the source cloud and from the partition management firmware of the destination cloud.
  - patent:
    title: Communications between virtual machines that have been migrated 
    ID: US8448171B2
    link: https://patents.google.com/patent/US8448171B2/en?q=inventor;sean&inventor=donnellan&oq=inventor;sean+donnellan
    abstract: |
      A method, apparatus, and computer program product for managing communications between a plurality of applications are presented. A determination is made as to whether an address in a message is a prior address for a second application in the plurality of applications in response to receiving a message from a first application in the plurality of applications. The message is sent onto a virtual network configured to handle prior addresses for the plurality of applications in response to the address in the message being the prior address for the second application being located on another virtual machine from the first application.
  - patent:
    title: Method and apparatus for providing a test network as an IP accessible cloud service
    ID: US9286103B2
    link: https://patents.google.com/patent/US9286103B2/en?q=inventor;sean&inventor=donnellan&oq=inventor;sean+donnellan
    abstract: A method and structure for a cloud service includes an API (application programming interface) as tangibly embodied in a set of computer-executable instructions and selectively executable on a computer on a network. The API provides a user interface for a cloud environment comprising one or more virtual machines to be selectively instantiated on at least one computer in the network upon a user request. A library is accessible via the API, the library providing definitions of components available to be instantiated in the cloud environment. The API automatically instantiates an image of a virtual network of components, as defined by a user input request and provides at least one cloud portal providing the user an access to exercise the instantiated virtual network image.
  - patent:
    title: Deploy a secure customer domain in a virtualized multi-tenant environment 
    ID: DE112014002799T5
    link: https://patents.google.com/patent/US9286103B2/en?q=inventor;sean&inventor=donnellan&oq=inventor;sean+donnellan
    abstract:  To provide a secure customer domain in a virtualized multi-tenant environment, a virtual machine (VM) is configured in a customer domain. A first, a second, and a third network interface (VNICs) are configured in the VM. The first VNIC has a first network address in a first address range for a customer domain and allows an application in the VM to access a second application in a second VM in the customer domain. The second VNIC allows a third application outside the customer domain to access the VM in the customer domain. The second VNIC is configured to utilize an address specification used by the server and the third application. The third VNIC allows access from the first application to a fourth application running outside the customer domain. The third VNIC is configured to use an address specification used by the server of the fourth application. 
 
#adding to the templates
projects:
  - project:
    period: 1999
    duration: 9 months
    role: test
    description: text goes here
    contributions: other text goes here
  - project:
    period: 2000
    duration: 9 months
    role: test
    description: text goes here
    contributions: other text goes here
  - project:
    period: 12/1997 - 04/2000
    duration: 29 months
    clientType: Consulting
    codeName: Firewall Dept.
    role: Senior Systems Engineer
    description: |
      Create firewall selling and design capabilities within the company. 
      Provide security expertise to customers. 
      Improve the companies own internal network security and provide secure access to the Internet and partners.
    contributions: |
      Created the Firewall dept.</br> Designed and built the company Internet and Extranet connectivity.</br> Designed the company Intranet proxy systems.</br> Provided customers with security expertise.</br> Designed and built numerous, multi tier, corporate firewall systems for banks, retail industry, manufacturing industry, and utility companies (based on Cisco, IBM, and Microsoft products).</br> Designed companies Extranet connectivity.</br> Designed anti virus solutions and so on.

  - project:
    period: 04/1997 - 12/1997
    duration: 9 months
    clientType: Large Bank
    codeName: GroGa
    role: System Engineer
    description: |
      Move 200+ stock trader workstations and the complete stock trader data center to a new location. 
      Move was in parallel with live operations.
    contributions: |
      Created automated remote AIX installation scripts to perform activities including root disk mirroring, 
      monitoring of HACMP and Highly Available Network File Systems (HANFS) disk partition integrity, 
      automation testing,
      HA testing,  
      and application testing.
      I wrote a web based problem ticket system for the team (>30 people).
      Assisted in the development of the configuration Graphical User Interface (CMDB) and software which was used to provision servers and workstations.
